last_accessed: 01-01-2001

email: 
from: 
password: 

gmail:
    imap_server: imap.gmail.com
    pop_server: pop.gmail.com
    pop_port: 995
    smtp_server: smtp.gmail.com
    imap_port: 993

flags:
    wiki: [wiki]
    edit: [e]
    create: [c]
    append: [a]
