last_accessed: 01-01-2001

email: example@email.com
from: example@email.com
password: somepassword

gmail:
    imap_server: imap.gmail.com
    imap_port: 993
    pop_server: pop.gmail.com
    pop_port: 995
    smtp_server: smtp.gmail.com
    smtp_port: 587

flags:
    wiki: [wiki]
    edit: [e]
    create: [c]
    append: [a]
